version: 2.1

orbs:
  coveralls: coveralls/coveralls@2.2.5

jobs:
  test-python:
    docker:
      - image: cimg/python:3.12
    environment:
      SECRET_KEY: "clave_secreta_para_tests_circleci"
      PYTHONPATH: "."
    steps:
      - checkout
      - run:
          name: Install uv
          command: pip install uv
      - run:
          name: Install dependencies
          command: uv sync
      - run:
          name: Run tests with coverage
          command: uv run coverage run --source=app -m pytest tests/ -v --junitxml=junit.xml
      - run:
          name: Upload coverage to Coveralls
          command: uv run coveralls --verbose
      - store_test_results:
          path: junit.xml

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Plan deployment
          command: |-
            circleci run release plan deploy \
              --environment-name="default" \
              --component-name="deploy" \
              --target-version="1.0.${CIRCLE_BUILD_NUM}-${CIRCLE_SHA1:0:7}"
      - run:
          name: deploy
          command: '#e.g. ./deploy.sh'
      - run:
          name: Update deployment status to running
          command: circleci run release update deploy --status=RUNNING
      - run:
          name: Update deployment status to success
          command: circleci run release update deploy --status=SUCCESS
          when: on_success
      - run:
          name: Update deployment status to failed
          command: circleci run release update deploy --status=FAILED
          when: on_fail

workflows:
  build-and-test:
    jobs:
      - test-python
